# Generated by Django 3.0.7 on 2020-09-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200913_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freebie',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
