# Generated by Django 3.1.5 on 2021-01-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('account_count', models.IntegerField(blank=True, null=True)),
                ('stock_id', models.IntegerField(blank=True, null=True)),
                ('screen_name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
